---
title: "Literature of Risk Sharing"
author: "Mizuhiro Suzuki"
date: "5/18/2019"
bibliography: risksharing.bib
output:
  html_document:
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(nleqslv)
library(ggplot2)
library(ggrepel)
library(shiny)
library(shinythemes)
```

In this document I introduce studies related to risk-sharing.
Here, by risk-sharing, I consider studies trying to understand the relationships between consumption and income and mechanisms to reduce the correlation through sharing income risks with others.
The seminal paper in this literature is @Townsend1994, and I introduce studies before and after this paper and try to relate each other.
@Fafchamps2011 reviews this literature extensively, and @Ligon2016 provides a brief (and super awesome!) review of this literature.

# Canonical full risk-sharing model

## Model

## Tests of full risk-sharing model in the U.S.

There are several studies applying the above estimation equation to the US data.
One of the main focuses of these studies is th test of market completeness:
under ...

### @Mace1991

She uses Consumer Expenditure Survey (CES) in the U.S. for 1980-1983 and analyzes how, controlling for changes in aggregate consumption, idiosyncratic shocks affect changes in individual consumption.
It should be noted that CES is an overlapping panel data of 1-year duration with a quarterly sampling frequency, which makes Townsend-like regressions possible.
Here, the whole economy is considered as one "village", implying that risk is presumably shared within the economy.
She finds that, while the economy almost achieves full risk-sharing under the CARA utility function, the full risk-sharing hypothesis is rejected under the CRRA utility function for many goods.

While she runs regressions with the same specifications as in @Townsend1994, there are a couple of differences from the study.
First, she runs regressions for, in addition to total consumption, different expenditure categories separately (services, nondurables, durables, food, housing, utilities, household furnishings, clothing, medical care, transportation, and recreation).
Under full risk-sharing, given that aggregate consumption is controlled for, idiosyncratic shocks should not affect each component of expenditures.
Secondly, she uses not only income shocks but also employment shocks and sees if they also affect individual consumption.
Again, under full risk-sharing, controlling for aggregate consumption, these non-income shocks should not affect individual consumption as well.
Also, in the appendix, she argues that the econometric specification in the paper is valid in the case with multiple goods under general homothetic utility function and with durable goods, although the latter holds under the assumption that the initial endowment of durable goods is identical to the distribution of Pareto weights. 

### @Cochrane1991

He uses Panel Study of Income Dynamics (PSID) in the U.S. for 1980-1983 to analyze how exogenous shocks affect consumption growth.
In his regressions, the left-hand side variable is consumption growth from 1980 to 1983, and the right-hand side variables are cumulated shocks from 1981 to 1983 such as unemployment or illness.
Although he also uses income shocks, interestingly he is suspicious of using income shocks, since income shocks can be correlated with the error term through, for example, preference shocks.
This can cause a spurious correlation between individual consumption and individual income, which can result in rejecting the full risk-sharing hypothesis.
Using the specification with the CRRA utility function, he finds that, while some shocks are insured (eg. light illness, strikes), other shocks are not (heavy illness, involuntary job loss).

### @Altonji1992

Although their framework does not exactly correspond to the full risk-sharing model, their empirical analysis is pretty close to other studies that test full risk-sharing hypothesis. 
In particular, they analyze if household consumption is correlated with household income, controlling for the aggregate resources of the extended family linked through altruism (for this control, they use extended-family fixed effects).
As mentioned in the paper, their dynamic tests (regressions with first-differences of variables) are equivalent to the test of full risk-sharing.
Their alternative hypothesis is the life-cycle model in which household consumption is determined by household income and resources of other households in the same extended family do not matter.

They use Panel Study of Income Dynamics (PSID) in the U.S. for 1976-1985.
PSID surveyed over 5000 households in 1968 and reinterviewed the heads and spouses of these sample each year since 1968. 
Importantly, when some household members form new households (eg. marriage of children), these new households are interviewed as well.
Connecting these child-households and original parent-households allows them to create a dataset of extended families with variables of each household.
They find that the altruism hypothesis is strongly rejected (household income affects household consumption), and the life-cycle model tends to be empirically supported (household consumption is little affected by resources of other households in the same extended family).

One thing that can be minor but interesting to me in the analyses is that they consider the possibility of labor supply (or leisure) being a choice variable.
Given that leisure is in the utility functions and wage rates are different across households, labor income may be positively correlated with, for example, food consumption since "higher wage rates -> more labor supply -> more food consumption (to compensate less leisure)".
To deal with this, they also use lagged wage in the analyses, and still the altruism hypothesis is strongly rejected (ie. lagged wage affects household consumption).

One motivation of this paper is to show that Barro's neutrality may not hold: that is, redistribution among members of an altruistically linked economic unit can change the unit's behaviors.
In the context of risk sharing in developing countries, this corresponds to the statement that redistribution among members in the same network can change their economic activities.
But this may be less relevant in the context of developing countries since policy interventions usually change aggregate resources of the communities and pure redistribution policies are rare.

## Risk-sharing under heterogeneity

In the theoretical part of this paper, @Cochrane1991 allows heterogeneous risk and time preferences across households.
However, in his "cross-sectional" analysis, if the economic shocks are independent of these variables, this heterogeneity does not matter for the test of full risk-sharing.
Also, @Townsend1994 conducts a time-series analysis for each household in ICRISAT data, which allows different preferrences for different households.
One problem in this analysis is the temporal length of the data: there are only 10 years of data, which seems too short to conduct a time-series anlaysis.
Here I will introduce works explicitly focusing on the heterogeneouos preferences of households in the context of risk sharing.

### @Kurosaki2001

To investigate how risk and time preferences affect the test of full risk-sharing as in @Townsend1994, he considers a model with a household-specific time discount factor ($\rho_i$) and utility function in which risk preferences can differ ($u_i(c_{ist})$).
Assuming an interior solution, as in @Townsend1994, the Pareto optimal allocation requires

$$
  \lambda_i \rho_i^t u_i'(c_{ist}) = \mu_{st} \quad \forall (s,t),
$$
where $\lambda_{i}$ is a Pareto weight for household $i$ and $\mu_{st}$ is the Lagrange multiplier associated with the feasibility constraint, devided by the probability that the state $s$ is realized in time $t$.
Assuming a CARA preferences with a household-specific coefficient of absolute risk aversion, $A_i$, we can derive an equation that looks similar to the one in a canonical risk-sharing model:

$$
  c_{it} = \alpha_i \overline{c}_t + \beta_i + \gamma_i t,
$$
where

\begin{align*}
  \alpha_i &= \frac{1}{A_i} \left[ \frac{1}{N} \sum_j \frac{1}{A_j} \right]^{-1} \\
  \beta_i  &= \frac{1}{A_i} \left[ \ln \lambda_i - \frac{1}{N} \sum_j \alpha_j \ln \lambda_j \right]^{-1} \\
  \gamma_i &= \frac{1}{A_i} \left[ \ln \rho_i - \frac{1}{N} \sum_j \alpha_j \ln \rho_j \right]^{-1},
\end{align*}

where $N$ is the number of households in the community.

This equation implies that 

1. $\alpha_i$ is smaller for a more risk averse household, and
2. $\gamma_i$ is more negative (ie. consumption decreases over time) for a more myopic household.

Note that, if there is no heterogeneity, $\alpha_i$ is common for all households and $\gamma_i = 0 \quad \forall i$.
A CRRA utility function results in a similar equation, but with log consumption.

To test whether (i) full risk sharing is achieved and (ii) there is any heterogeneity in terms of time and risk preferrences, with CARA utility functinos, the author estimate

$$
  \Delta c_{it} = b_i + a_i \Delta \overline{c}_t + \zeta_i X_{it} + u_{it},
$$

where $X_{it}$ is the first-different household income.
While this looks similar to the estimation equation in @Townsend1994, this equation is much more flexible due to household-specific intercepts and slopes.
Notice that here the effect of household income ($\zeta_i$) is household specific as well, which allows the author to see which households are more "vulnerable" in the sense that income and consumption are more correlated.
The estimation results suggest that (i) the full risk-sharing is not achieved, and (ii) there is heterogeneity among households in their sensitivity to aggregate and idiosyncratic shocks.
The author also investigates what variables are correlated with each of $b_i$, $a_i$, and $\zeta_i$.

One problem of this analysis is that, as pointed out in the paper, the interpretation of $b_i$ and $a_i$ is not clear when the full risk-sharing hypothesis is rejected.
As @Ligon2016 argues, given that the full risk sharing hypothesis is rejected, the theory does not provide an interpretation that the equation above is a consumption function.
In this sense, interpreting the estimates of $b_i$ and $a_i$ as something reflecting time and risk preferences can be misleading, and more complete model needs to explain why full risk-sharing fails while taking into account preference heterogeneity.
@Laczo2015 can be seen as a work attempting this, using dynamic limited commitment as the factor preventing full risk-sharing.

### @Schulhofer-Wohl2011

### @Mazzocco2012

### @Chiappori2014

# Failure of full risk-sharing: why?

Given that the full risk-sharing model has been rejected in many contexts, many studies have tried to explain the partial risk sharing.
In most of these studies, some form of friction is introduced to the model, and below I review these studies.

## Static limited commitment model

In the full risk-sharing model, it is assumed that transfers among households are enforced, but this can be challenging without formal institutions.
In limited commitment models, the possibility of defaulting the transfer rule is taken into account.
In the models, social planner's maximization problem is subject to enforceability constraints, where people do not renege on prior agreements on transfers.

In a *static* limited commitment model, transfer rules are not allowed to depend on past states.
The repeated game is used in the analysis, and @Coate1993 provides a simple and clear framework.

### @Kimball1988

In this paper, he provides a framework for risk-sharing with limited commitment and conducts numerical analyses to see (i) under what parameter values enforceability constraints are satisfied (and hence some form of transfers happens), and (ii) under what parameter values full risk-sharing is achieved.
Interestingly, in his formulation of the problem, he does not use the repeated game but instead uses the dynamic optimization, which looks closer to the dynamic limited commitment model (introduced below) in which transfers can depend on past states.
However, Kimball explicitly rules out the possibility of consumption depending on the past states (p.226), which makes the framework a static limited commitment model.

The paper says Table 1 shows that the enforceability constraints tend to be satisfied with reasonable parameters and Table 3 shows that full risk-sharing can be achieved with reasonable parameters.
I am not sure (i) what the expression for $W(P)$ on p.226 is, (ii) how to derive (6), and (iii) how to get numbers on Table 3.

The main motivation in this paper is to explain why farmers had scattered plots in Medieval England.
Some say this is for insurance (as a form of income diversification), but Kimball argues that this is unlikely since, as shown in the paper, risk-sharing among farmers as informal insurance can be sustained.
Thus, he argues that, rather than relying on the costly income diversification (eg. travel time), farmers should use risk-sharing for insurance.

### @Coate1993:

Like @Kimball1988, this paper also considers a risk-sharing model with limited commitment model.
Unlike @Kimball1988, however, their framework is based on an infinite-period repeated game:
in each period, players either follow a transfer schedule or renege and will stay in autarky forever.
Under symmetric income distribution, they compare first-best transfers under full risk-sharing and best implementable transfers (best in the sense that the transfers that maximize the expected utilities).

The problem considered in the paper is to maximize the average expected utility of a household (by symmetry, a transfer schedule that maximizes the average expected utility of one household maximizes that of the other household), subject to the following *implementability constraints*:

\begin{align*}
  u(y_i) - u(y_i - \theta_{ij}) &\le (v^A(\Theta) - \overline{v}) / r \quad \text{for all } (i, j) \\
  u(y_j) - u(y_j + \theta_{ij}) &\le (v^B(\Theta) - \overline{v}) / r \quad \text{for all } (i, j),
\end{align*}

where $y$ is income, $\theta_{ij}$ is the transfer from A to B when the state is $(i, j)$, $\Theta$ is the entire transfer schedule, or *informal insurance arrangement*, $\overline{v}$ is the value under autarky, and $r$ is the discount rate.
Using this framework, they examine (i) how the best implementable (ie. under the implementability constraints) insurance arrangement and the full risk-sharing insurance arrangement differ, and (ii) how the best implementable insurance arrangement changes with exogenous variables of the model (discount rate and correlation in income realizations).
Also, they conduct numerical exercises to show how changes in exogenous variables affect the insurance arrangement.
The numerical exercises 

As suggestions for future research (I mean, "future" from their perspective), they provide three possible directions to extend their model:

1. to allow non-stationary insurance arrangements, which can depend on both current and past income realizations;
2. to allow households to save;
3. to allow households' income to depend on its work effort which others in the community cannot observe.

Interestingly, all of these three extensions have been achieved by later works as shown below.

#### Difference between @Kimball1988 and @Coate1993

The main difference between this paper and @Kimball1988 is that, 

- while @Kimball1988 identifies the conditions (i) for risk-sharing institutions to exist and (ii) for full risk-sharing to be achieved,
- @Coate1993 investigates the properties of the best implementable insurance arrangement (ie. how this is different from the insurance arrangement under full risk-sharing and how this arrangement changes as exogenous variables vary).

## Dynamic limited commitment model

Unlike *static* limited commitment models, *dynamic* limited commitment models allow insurance arrangement to depend both on current and past income realizations, which allows more efficient risk-sharing.
As pointed out in @Ligon2002, in a sense static limited commitment models provide a framework to understand a system of gifts or transfers, whereas dynamic limited commitment models provide a framework for a system of mutual insurance through loans (borrowing when times are bad and repaying when times are good).

This model is largely based on the model in @Thomas1988.
In this paper, they consider self-enforcing wage contracts (ie. since there is no enforceable contract, both workers and employers can renege) and analyze how wages can be updated in response to market shocks (ie. changes in spot market wages).
They provide a simple update rule: "around each spot wage is a time invariant interval and the contract wage changes each period by the smallest amount necessary to bring it into the current interval."
The main figure in this paper is replicated [here](TW88_code.html).

Also, I feel this model is closely related to the model of relational contract, where there is no enforceable contract and the nature of repeated game helps players to behave in a certain way to maintain the long-term relationship.
Both models have commonality in the sense that relationships are sustained by the value of future relationships, even without any enforcement.

### @Kocherlakota1996:

### @Fafchamps1999:

### @Attanasio2000: 

### @Ligon2002:

### Interlude: Applications of dynamic limited commitment model 

#### @Albarran2003: 

#### @Krueger2006: In the U.S.

#### @Mazzocco2007: Intra-household decision makings

#### @Voena2015: Intra-household decision makings

#### @Kehoe2002: International business cycles

## Hidden income model

## Moral hazard model

### @Abraham2008:

### @Belhaj2012:

### @Belhaj2014:

## Something $\times$ something

### @Cole2001: Hidden income $\times$ storage

### @Laczo2015: Dynamic limited commitment $\times$ preference heterogeneity

### @Ligon2000: Dynamic limited commitment $\times$ (private) storage

### @Genicot2006: Dynamic limited commitment $\times$ wealth inequality

### @Abraham2018: Dynamic limited commitment $\times$ (both private and public) storage

# Formation of risk-sharing networks

# Risk-sharing with explicit networks

## @Ambrus2014:

# Others (pending)

@Fafchamps1992:

@Dizon2019: 

@Krueger2011: Dynamic limited commitment $\times$ public risk sharing (?)

@Udry1994:

# Key empirical findings so far

- High-level of risk sharing, but full risk-sharing is not achieved (@Mace1991, @Cochrane1991, @Townsend1994)
- State-contingent credits (@Udry1994)

# References



